### ISSUE TITLE
app gets stuck in loop installing certificate

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#212]
On Android 7.0, app version 0.4.2, databox tagged 0.3.0, then connecting to databox it repeatedly says "Install Certificate", I confirm (couple of steps), it shows toast "Databox is installed", but still re-shows "Install Certificate". Repeat...

Checking settings / security shows a databox certificate in the trusted list.

Checking logcat shows the following, unsure if it is related:
```
...
12-12 16:10:49.096 24353 24440 I SensingKit: http://192.168.0.9:8448/cert.pem
12-12 16:10:49.098 24353 24353 D SystemWebChromeClient: file:///android_asset/www/index.html: Line 0 : Uncaught (in promise) TypeError: Failed to fetch
12-12 16:10:49.098 24353 24353 I chromium: [INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///android_asset/www/index.html (0)
...
12-12 16:10:55.804 23629 23629 D CertInstaller: credential is added: Databox
...
12-12 16:10:56.104 24353 24353 D CordovaActivity: Incoming Result. Request code = 692
12-12 16:10:56.105 24353 24353 D CordovaInterfaceImpl: Sending activity result to plugin
12-12 16:10:56.105 24353 24353 W System.err: java.lang.UnsupportedOperationException
12-12 16:10:56.105 24353 24353 W System.err: 	at com.android.org.conscrypt.TrustedCertificateKeyStoreSpi.engineSetCertificateEntry(TrustedCertificateKeyStoreSpi.java:77)
12-12 16:10:56.105 24353 24353 W System.err: 	at java.security.KeyStore.setCertificateEntry(KeyStore.java:1003)
12-12 16:10:56.105 24353 24353 W System.err: 	at uk.ac.nott.mrl.sensingKit.SensingKit.createTrustManagerFactory(SensingKit.java:256)
12-12 16:10:56.105 24353 24353 W System.err: 	at uk.ac.nott.mrl.sensingKit.SensingKit.onActivityResult(SensingKit.java:581)
12-12 16:10:56.105 24353 24353 W System.err: 	at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:152)
12
...
```

**Comment by Toshbrown** [comment]
@ktg has fixed this. Can't reproduce on iso or android.
