### ISSUE TITLE
Databox won't start - missing node package

### ISSUE THREAD

**Issue by ghost** [me-box/databox#242]
When running the databox-start script, I get the following: 

```
databox@databox-nuc-1:~/databox$ git pull
Already up-to-date.
databox@databox-nuc-1:~/databox$ ./databox-start
[2018-02-22 09:51:15 databox-start]: testing if Databox is already running ...
[2018-02-22 09:51:15 databox-start]: extracting host interface IP address ...
[2018-02-22 09:51:15 databox-start]: host interface IP address = 192.168.1.108
[2018-02-22 09:51:15 databox-start]: Starting version 0.3.2
[2018-02-22 09:51:15 databox-start]: Creating Certificates
module.js:557
    throw err;
    ^

Error: Cannot find module 'qrcode'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/cwd/src/createCerts.js:5:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
[2018-02-22 09:51:16 databox-start]: Starting the Databox swarm
Swarm initialized: current node (xwdmejnwcuenii96z7u72k4u2) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-542008sfsk9sl2ppueylrwbb9q16znbvpnc5cxou7qzq7y5cu8-4fpppppqrisf7c8je8lnqkxe3 192.168.1.108:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

[2018-02-22 09:51:16 databox-start]: Starting Databox
sikgemjr4szbqpk669cx48fp2
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating databox_databox-network_1 ... done
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

WARNING: Found orphan containers (databox_databox-network_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating databox_app-server_1 ... done
Creating network databox_databox-cm-app-server-net
open /home/databox/databox/certs/rootCert.crt: no such file or directory
[2018-02-22 09:51:20 databox-start]: ERROR: Problem with docker stack deploy
```

**Comment by Toshbrown** [comment]
Try this:

```
rm -rf ./node_modules
```

then restart
