### ISSUE TITLE
Syntax error -development branch 

### ISSUE THREAD

**Issue by pooyadav** [me-box/databox#32]
Databox UI can be accessed at http://127.0.0.1:8989
undefined:1
`<html>`
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.request [as _callback] (/src/server.js:181:21)
    at Request.self.callback (/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
    at IncomingMessage.<anonymous> (/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:291:19)

**Comment by pooyadav** [comment]
This was coming in Raspberry pi because server is down at http://store.upintheclouds.org
