### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by pooyadav** [me-box/databox#33]
Using default tag: latest
latest: Pulling from databoxsystems/databox-cm-arm
38eeefe0e5fb: Pull complete 
199b8e4d0468: Pull complete 
c0576677e09e: Pull complete 
897374840dc1: Pull complete 
95e1ab48946f: Pull complete 
3fa139e274d2: Pull complete 
6ca0e5b1863e: Pull complete 
fc05213ef84c: Pull complete 
8920336c0edb: Pull complete 
e641980df65f: Pull complete 
14e5ad93c0ab: Pull complete 
1c6305adf503: Pull complete 
0938df22c1a1: Pull complete 
168ce8545c24: Pull complete 
339ae021e771: Pull complete 
8937c959ddfa: Pull complete 
Digest: sha256:74e6eacfd1724471dc3a9be7ee38cb6f83fdfe2b76eecb763cfba361ab384516
Status: Downloaded newer image for databoxsystems/databox-cm-arm:latest
npm info it worked if it ends with ok
npm info using npm@4.1.2
npm info using node@v7.6.0
npm info lifecycle databox-container-manager@0.1.0~prestart: databox-container-manager@0.1.0
npm info lifecycle databox-container-manager@0.1.0~start: databox-container-manager@0.1.0

> databox-container-manager@0.1.0 start /
> node src/main.js

ERROR creating databox-external { Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
ERROR creating databox-cm-arbiter-net { Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
npm info lifecycle databox-container-manager@0.1.0~poststart: databox-container-manager@0.1.0
npm info ok 
/usr/bin/entry.sh: line 93: fg: job has terminated

**Comment by Toshbrown** [comment]
Try adding your user to the docker group or run with sudo.

**Comment by pooyadav** [comment]
I did run with sudo, but still  error for arbiter and export service. Had to switched user to root and it worked fine. Will  try by adding user to the docker group
