### ISSUE TITLE
databox-logstore connection error ARM

### ISSUE THREAD

**Issue by pooyadav** [me-box/databox#35]
2017-04-18T13:12:33.072526504Z npm info it worked if it ends with ok
2017-04-18T13:12:33.074827228Z npm info using npm@4.1.2
2017-04-18T13:12:33.075559361Z npm info using node@v7.6.0
2017-04-18T13:12:34.446369719Z npm info lifecycle databox-logstore@1.0.0~prestart: databox-logstore@1.0.0
2017-04-18T13:12:34.491546798Z npm info lifecycle databox-logstore@1.0.0~start: databox-logstore@1.0.0
2017-04-18T13:12:34.509007329Z 
2017-04-18T13:12:34.509177121Z > databox-logstore@1.0.0 start /
2017-04-18T13:12:34.509219568Z > node ./src/main.js
2017-04-18T13:12:34.509249464Z 
2017-04-18T13:12:36.485333578Z [databox-request] https://databox-arbiter:8080/store/secret
2017-04-18T13:12:36.669738605Z { Error: getaddrinfo ENOTFOUND databox-arbiter databox-arbiter:8080
2017-04-18T13:12:36.669882042Z     at errnoException (dns.js:28:10)
2017-04-18T13:12:36.669916781Z     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
2017-04-18T13:12:36.669949438Z   code: 'ENOTFOUND',
2017-04-18T13:12:36.669977823Z   errno: 'ENOTFOUND',
2017-04-18T13:12:36.670006469Z   syscall: 'getaddrinfo',
2017-04-18T13:12:36.670034906Z   hostname: 'databox-arbiter',
2017-04-18T13:12:36.670063656Z   host: 'databox-arbiter',
2017-04-18T13:12:36.670092927Z   port: '8080' }
2017-04-18T13:12:36.708958927Z npm info lifecycle databox-logstore@1.0.0~poststart: databox-logstore@1.0.0
2017-04-18T13:12:36.763037964Z npm info ok 
2017-04-18T13:12:36.829954314Z /usr/bin/entry.sh: line 93: fg: job has terminated

**Comment by pooyadav** [comment]
2017-04-18T13:12:33.078876072Z npm info it worked if it ends with ok
2017-04-18T13:12:33.081430493Z npm info using npm@4.1.2
2017-04-18T13:12:33.082397730Z npm info using node@v7.6.0
2017-04-18T13:12:34.479537452Z npm info lifecycle databox-container-manager@0.1.0~prestart: databox-container-manager@0.1.0
2017-04-18T13:12:34.539236476Z npm info lifecycle databox-container-manager@0.1.0~start: databox-container-manager@0.1.0
2017-04-18T13:12:34.558254607Z 
2017-04-18T13:12:34.558421325Z > databox-container-manager@0.1.0 start /
2017-04-18T13:12:34.558458096Z > node src/main.js
2017-04-18T13:12:34.558490752Z 
2017-04-18T13:13:13.426824808Z Cant connect to docker!
2017-04-18T13:13:13.430450321Z Error
2017-04-18T13:13:13.430583602Z     at httpsHelper.init.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.catch.err (/src/main.js:156:17)
2017-04-18T13:13:13.430619487Z     at process._tickCallback (internal/process/next_tick.js:103:7)
2017-04-18T13:13:13.455077709Z npm info lifecycle databox-container-manager@0.1.0~poststart: databox-container-manager@0.1.0
2017-04-18T13:13:13.488863566Z npm info ok 
2017-04-18T13:13:13.526665923Z /usr/bin/entry.sh: line 93: fg: job has terminated

**Comment by Toshbrown** [comment]
Fixed in 0c92150be1449c0987b876830cded977b4493fbb
