### ISSUE TITLE
DNS error app-server 

### ISSUE THREAD

**Issue by pooyadav** [me-box/databox#57]
databox_container-manager.1.9281t3i49ijj@moby    | Using dev registry:: 
databox_container-manager.1.9281t3i49ijj@moby    | Starting UI Server!!
databox_container-manager.1.9281t3i49ijj@moby    | Error: http://app-server:8181/app/list
databox_container-manager.1.9281t3i49ijj@moby    | [Error]  { Error: getaddrinfo ENOTFOUND app-server app-server:8181
databox_container-manager.1.9281t3i49ijj@moby    |     at errnoException (dns.js:50:10)
databox_container-manager.1.9281t3i49ijj@moby    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:91:26)
databox_container-manager.1.9281t3i49ijj@moby    |   code: 'ENOTFOUND',
databox_container-manager.1.9281t3i49ijj@moby    |   errno: 'ENOTFOUND',
databox_container-manager.1.9281t3i49ijj@moby    |   syscall: 'getaddrinfo',
databox_container-manager.1.9281t3i49ijj@moby    |   hostname: 'app-server',
databox_container-manager.1.9281t3i49ijj@moby    |   host: 'app-server',
databox_container-manager.1.9281t3i49ijj@moby    |   port: '8181' }
databox_container-manager.1.9281t3i49ijj@moby    | Error: http://app-server:8181/app/list
databox_container-manager.1.9281t3i49ijj@moby    | [Error]  { Error: connect ECONNREFUSED 10.0.3.4:8181
databox_container-manager.1.9281t3i49ijj@moby    |     at Object.exports._errnoException (util.js:1022:11)
databox_container-manager.1.9281t3i49ijj@moby    |     at exports._exceptionWithHostPort (util.js:1045:20)
databox_container-manager.1.9281t3i49ijj@moby    |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
databox_container-manager.1.9281t3i49ijj@moby    |   code: 'ECONNREFUSED',
databox_container-manager.1.9281t3i49ijj@moby    |   errno: 'ECONNREFUSED',
databox_container-manager.1.9281t3i49ijj@moby    |   syscall: 'connect',
databox_container-manager.1.9281t3i49ijj@moby    |   address: '10.0.3.4',
databox_container-manager.1.9281t3i49ijj@moby    |   port: 8181 }
^C

**Comment by pooyadav** [comment]
Resetting Docker solved this.
