### ISSUE TITLE
App-store connection error

### ISSUE THREAD

**Issue by pooyadav** [me-box/databox#58]
[seeding manifest] get app store root to log in { Error: connect ECONNREFUSED 127.0.0.1:8181
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8181 }
undefined

**Comment by Toshbrown** [comment]
I need a bit more info on how/when this happened to have any chance of tracking it down. 

Cheers 

Tosh

**Comment by Toshbrown** [comment]
fixed in #61
